### ISSUE TITLE
Schema Repository - default UUID on start

### ISSUE THREAD

**Issue by esavier** [epiphany-platform/CommonDataLayer#10]
I would like to be able to pass the command line switch to the schema repository to force auto-creation of default schema. i.e.
./schema_repository --default-schema

**Comment by luke-biel** [comment]
Maybe we'd allow to pre-load schemas from config? Like we initialize postgres.

**Comment by luke-biel** [comment]
Closed by #14

**Comment by esavier** [comment]
reopening

**Comment by esavier** [comment]
fixed by import feature
