### ISSUE TITLE
Query Service - add "RAW" path

### ISSUE THREAD

**Issue by luke-biel** [epiphany-platform/CommonDataLayer#16]
Query Service should be able to send raw query to known database, even if common api does not support it.

This task has only timeseries query service in mention.

Acceptance criteria:
* [ ] `query-service-ts` has to be able to accept `Raw` grpc query, that would be passed directly to database, without translation process
* [ ] raw queries are integration tested

**Comment by esavier** [comment]
not sure, but i would assume that there will be required some kind of field that is able to tell app that this query is raw or not, i.e. {rawtype:true} or something like that
