### ISSUE TITLE
Simple message decomposition in DataRouter

### ISSUE THREAD

**Issue by esavier** [epiphany-platform/CommonDataLayer#161]
I would like DataRouter to be able to process multimessages. That means  receiving:
```
(pseudocode)
[ 
  {id:1,schema:1,data:{}}
  {id:2,schema:1,data:{}}
  {id:3,schema:1,data:{}}
  {id:4,schema:2,data:{}}
  {id:5,schema:3,data:{}}
]
```
and splitting those into single json messages (extracting from list to single objects)

**Comment by frondeus** [comment]
Whats the difference between this task and #210 ?

**Comment by Kononnable** [comment]
Looks like the same feature, we forgot to close the issue.
