### ISSUE TITLE
Load configuration files instead of depending on env variables/command line args

### ISSUE THREAD

**Issue by frondeus** [epiphany-platform/CommonDataLayer#184]
**Is your feature request related to a problem? Please describe.**
Command-line arguments/env variables are pretty limiting. Especially with `structopt`/`clap`
Whenever I have to write a code that should read env variables for something more complex, like choosing between RabbitMQ and Kafka, I have to manually write a lot of boilerplate.

**Describe the solution you'd like**
I think configuration files, either TOML or simple JSON format, would significantly reduce complexity. However, this has to be done with caution. A lot of information passed via ENV variables are secrets. Stuff like credentials, passwords, tokens cannot be stored in plain files. 

There has to be a way to inject these configs via ENV vars. Therefore config files would be an extension, not a replacement.

I think the most elegant solution would be a templated config file: (JSON only as an example)
```json
{
     "messageQueue": {
         "type": "rabbitmq",
         "connectionString": "{{ CONNECTION_STRING }}",
     }
}
```

Unfortunately, that would require writing a new utility crate or module to handle it, but it isn't rocket science.

**Comment by esavier** [comment]
libs from this family can prove to be useful for this
https://lib.rs/crates/expand_str
https://lib.rs/crates/hbsenvsubst

**Comment by frondeus** [comment]
Blocked for now because #229 may solve this issue

**Comment by frondeus** [comment]
I'd say it's done via #470
