### ISSUE TITLE
CDL should support both Kafka and RabbitMQ.

### ISSUE THREAD

**Issue by frondeus** [epiphany-platform/CommonDataLayer#192]
**Is your feature request related to a problem? Please describe.**
Both Kafka and RabbitMQ need to be supported in CDL modules. There should be no vendor locking. The client should be able to choose whether he likes to have only Kafka, or RabbitMQ installed on his cluster and CDL should just work.

**Describe the solution you'd like**
Whoever is deploying CDL should choose via a config file or env var what message queue should be used.

**Comment by luke-biel** [comment]
We may look into `clap` for loading config files, as it supports yaml loading. We were anyway considering using clap instead of structopt https://github.com/epiphany-platform/CommonDataLayer/issues/187

**Comment by luke-biel** [comment]
Fixed in #189
