### ISSUE TITLE
Ordering is not optional

### ISSUE THREAD

**Issue by esavier** [epiphany-platform/CommonDataLayer#218]
ordering introduced in 0.2.0 is not optional,
this have to be patched in 0.2.1

**Comment by Kononnable** [comment]
Ordering is optional, data router is always running with keeping order of messages. Single component running in 'ordered mode' doesn't make whole system 'ordered' but can result in performance degradation.

**Comment by Kononnable** [comment]
@esavier  Can this be closed now, or is there anything else that needs to be done before marking this issue as resolved?

**Comment by frondeus** [comment]
I see no answer, after fixes from @Kononnable it seems that ordering is optional again.
I'm closing this issue.
If you feel the urge to discuss it or you find a case where ordering is not opt-in - please reopen this issue or create a new one.
