### ISSUE TITLE
Ingestion protocol schema versioning

### ISSUE THREAD

**Issue by luke-biel** [epiphany-platform/CommonDataLayer#225]
rfc tracking issue: https://github.com/epiphany-platform/CommonDataLayer/pull/238

[rendered](https://github.com/epiphany-platform/CommonDataLayer/blob/rfc/cim-versioning/docs/rfc/protocol_version.md)

**Comment by frondeus** [comment]
We need to define better **why** we need this feature and what problem it solves.

**Comment by Kononnable** [comment]
As stated in RFC - for now we're not introducing any schema version field. We'll introduce it once there is a need for it(e.g. when first non-backward compatible change is introduced).
