### ISSUE TITLE
feat: Consider changing sledb to some distributed database

### ISSUE THREAD

**Issue by Kononnable** [epiphany-platform/CommonDataLayer#243]
Consider changing sledb to some distributed database:
- it will take care of replication and similar topics
- currently we're locked on branch-based sled for schema registry - new sledb/indradb combination doesn't work with azurefiles

Projects worth taking look at:
- TiKV https://tikv.org/
- Apache Druid https://druid.apache.org/

**Comment by luke-biel** [comment]
We can look into `apache druid,` which was initially proposed for this purpose. I know it's probably slow, but it should be at least looked into.

**Comment by esavier** [comment]
i believe we can close it now? we have Postgres for now as a SR backend and p2p feature is inbound

**Comment by Kononnable** [comment]
We have or we'll have once it is merged?
