### ISSUE TITLE
Proper handling of invalid messages

### ISSUE THREAD

**Issue by Kononnable** [epiphany-platform/CommonDataLayer#261]
We should properly handle messages which are invalid. Currently we ignore such messages or restart the service - DoS because of constant service restart or no ability to acknowledge following messages(since invalid message was not acked).

Example of place which need more love(issue affect most of the services)
https://github.com/epiphany-platform/CommonDataLayer/blob/3b25fded3df09e6c3a0ae418d7d1872ac721ef96/crates/command-service/src/input/service/message_queue.rs#L114-L115

**Comment by frondeus** [comment]
@Kononnable - Is this still valid? I have an impression we fixed it

**Comment by Kononnable** [comment]
It looks like that one is fixed. 
I don't see any `abort` nor `expect` in our code in places that should fail only a single message.
