### ISSUE TITLE
Document service configuration

### ISSUE THREAD

**Issue by luke-biel** [epiphany-platform/CommonDataLayer#289]
The configuration is currently scattered between service documentations. WE should prepare one document where all environment variables live.

**Comment by frondeus** [comment]
There will be a fifth place to maintain them:
* In Rust code (doc comments)
* In `docs/architecture/<service>.md`
* In `docs/configuration.md`
* In `deployment/helm` files
* In `deployment/compose` files

While the last two are inevitable, we should think about simplifying the process for the first three.

**Comment by frondeus** [comment]
I added related #310

**Comment by Kononnable** [comment]
If we have to choose I would propose single place in docs.

I don't think docs comments are problematic. They're kept with code so its pretty easy to change them(you won't forget about it). As for its usability - mostly for bare metal users.

Why single place not per each service?
Some configuration variables are quite common. E.g. if we expose kafka configuration(#249) as environmental variables those variables will be same for almost every service. There is no need to document them separately. I think most users will set up all of  CDL components at the same time, so they'll require all of this knowledge anyway.

**Comment by frondeus** [comment]
> I don't think docs comments are problematic. They're kept with code so it's pretty easy to change them(you won't forget about it). As for its usability - mostly for bare metal users.

The issue I see is the fact that you need to keep all docs in sync. I don't want to have a situation where someone modifies only docs but forget about code and vice versa.

**Comment by luke-biel** [comment]
From discussions it appears there is consensus that we want to keep documentation spec in `docs/configuration` directory only. There is upcoming meeting which will result in actions that will help us keep them up to date. I'm closing it for now.
