### ISSUE TITLE
Improve Efficiency of Expensive Operations in the Command Service(s)

### ISSUE THREAD

**Issue by USSAMOH2** [epiphany-platform/CommonDataLayer#31]
Though not necessary everywhere, we should have at least close to best possible behavior in the most intensive parts of our application(s). In the [given line](https://github.com/epiphany-platform/CommonDataLayer/blob/dd60f5a42d077c612a2e140fb113c3ee1c9d1783/command-service/src/input/service.rs#L66), we perform way more than necessary allocation. There are other frequent operations that could be given good attention.

**Comment by luke-biel** [comment]
This was taken care of
