### ISSUE TITLE
Script scrapping StructOpt `--help` messages to create tables in markdown.

### ISSUE THREAD

**Issue by frondeus** [epiphany-platform/CommonDataLayer#310]
**Is your feature request related to a problem? Please describe.**
Right now every time someone changes an environment variable name or add a new one, needs to edit several different places in our codebase:
* In Rust code (doc comments)
* In docs/architecture/<service>.md
* In docs/configuration.md
* In deployment/helm files
* In deployment/compose files

While the last two are inevitable, we should think about simplifying the process for the first three.

**Describe the solution you'd like**
We can leverage the fact, that StructOpt generates `--help` output and parse it to collect all ENV variables with descriptions, information about optionality, and default values. 

Then it can create automatically-generated markdown files that we can include (with mdbook support) to the handwritten documentation.

This solution would need some extra mechanism to introduce examples because StructOpt does not support it. One option could be to have "ex. `1234`" in the description (in *.rs in doc comment) and then detect it and parse it separately.

**Describe alternatives you've considered**
Instead of parsing `--help` output which might be hard, we could also create a custom derive macro that would live alongside with `StructOpt`, that would understand `StructOpt` args syntax. This macro could also introduce its own attribute for `example` which removes the need for extra "ex. `1234`" parsing.

**Comment by Kononnable** [comment]
Implementator should probably remember about #187 
I'm not sure if that issue is not blocked by #289 - we probably should decide how we want to approach this part of docs first.

**Comment by esavier** [comment]
from what i planned so far it would be basically a bash script, but sure it may change with introduction of configuration service.
technically the good idea would also be to provide the default config file for config service (i.e. deriving default for all config structs and serializing it to file on demand). That would make scrapping far easier.

**Comment by frondeus** [comment]
Seems to be obsolete, there is an RFC - #607 that describes what to do

**Comment by luke-biel** [comment]
To be specific, https://github.com/epiphany-platform/CommonDataLayer/issues/630 superseedes this
