### ISSUE TITLE
Add ability to filter by [(relation, schema_id, object_id)] to Edge repository

### ISSUE THREAD

**Issue by esavier** [epiphany-platform/CommonDataLayer#395]
- [ ] Filters can be set on multiple schemas at once
- [ ] One schema can be used multiple times in a view(once using relation A, once relation B)  -  filtering should be applied per relation

**Comment by luke-biel** [comment]
From discussion with @Kononnable we came to conclusion that this is currently covered in sufficient percent (it was partially implemented with Tree query).
