### ISSUE TITLE
bug: Duplicated notifications

### ISSUE THREAD

**Issue by esavier** [epiphany-platform/CommonDataLayer#403]
### In the report from third party we got info that we are processing requests more than once. We have to reproduce it and address it.

- Tested version - 
- - this is weird, its the issue of either version 0.2.0 or devel (taken from guest's release page), there are no more info available
- Tested configuration - kafka only
- deployment type - single instance with kubernetes, unknown number of worknodes
- kafka configuration is not known
- cdl configuration is not known
- enabled ordering
- find which version it was

#### taskslist:

- [ ] identify problem and propose solution
- [ ] solution is implemented
- [ ] testing was performed
- [ ] patch for 1.0.0
- [ ] user documentation

####  notes:
- RFC is not required
- documentation required only if there are visible changes like configuration or unexpected behavior 
- Test and develop against development branch

**Comment by Kononnable** [comment]
@esavier What are the acceptance criteria? I don't think anyone reproduced the issue so far, and without possibility of reproducing(or seeing logs etc.) not much we can do about that.

**Comment by frondeus** [comment]
Decision: Lets check devel and see if its still a problem, we are not supporting versions before 1.0.0.

**Comment by frondeus** [comment]
Couldn't reproduce close. If somebody can reproduce, please reopen this issue with logs.
