### ISSUE TITLE
chore: build system access and setup

### ISSUE THREAD

**Issue by esavier** [epiphany-platform/CommonDataLayer#422]
* [x] @luke-biel has access to playground
* [x] @pgr-automation has access to playground
* [x] @frondeus  has access to playground
* [x] @Kononnable  has access to playground
* [x] @smores56 has access to playground

**Comment by esavier** [comment]
waiting for DevOps response

**Comment by frondeus** [comment]
@esavier  - if this is related to CBS, can we close it?

**Comment by esavier** [comment]
@smores56 ?
