### ISSUE TITLE
Create examplary CDL client

### ISSUE THREAD

**Issue by luke-biel** [epiphany-platform/CommonDataLayer#43]
We need to pick some popular languages and write clients for CDL that allow user to `insert new data`, `retrieve stored data` and `create schemas` (only doc repo for now). These should be simple examples.

Languages to consider:
- [x] Python
- [ ] Rust
- [ ] Go
- [ ] C# or Java
- [ ] JS/TS

**Comment by esavier** [comment]
dropping this issue. We have too much to do to worry about different implementations,
Python is ready, we will go back to this when the need arise.
