### ISSUE TITLE
bug: Query service doesn't validate schema_id on QueryMultiple route

### ISSUE THREAD

**Issue by luke-biel** [epiphany-platform/CommonDataLayer#52]
As in title. It seems as something that some day may cause problems. But may as well not. We need to discuss whether to ignore this behaviour or change it.

**Comment by esavier** [comment]
put it in the config :D

**Comment by frondeus** [comment]
By "doesn't validate" do you mean "It does not check whether schema_id is a proper UUID". or "It does not check whether schema with this schema_id exists"?
