### ISSUE TITLE
feat: Apply changes defined in RFC Edge registry - Resolving relation trees

### ISSUE THREAD

**Issue by luke-biel** [epiphany-platform/CommonDataLayer#523]
- [ ] change tree query request/response formats
- [ ] add advanced support filtering to ER
- [ ] add the ability to ER to query relation by both sides
- [ ] resolving relation trees should be handled by using the `inner join` strategy
- [ ] remove ListRelations Grpc request/response
- [ ] change GetRelation Grpc request/response to be able to handle multiple relations(should we rename it to plural?)

**Comment by luke-biel** [comment]
One thing to consider - is postgres still a good for ER purposes or should we swap it out?

**Comment by Kononnable** [comment]
It should be fine - adding index so searching by any side of the relation is covered by index should be enough(in terms of performance).

**Comment by luke-biel** [comment]
that's an assumption though, not a fact

**Comment by frondeus** [comment]
TODO: Merge this issue with orther issues connected to #581
