### ISSUE TITLE
Add more logs to Schema Repository

### ISSUE THREAD

**Issue by esavier** [epiphany-platform/CommonDataLayer#54]
In case of errors, Schema repository is not debuggable aside H2 protocol traces. Please increase amount of logs being produced by schema repository logic

**Comment by luke-biel** [comment]
What's acceptance criteria of this? Some changes are added with `tracing`. @esavier

**Comment by esavier** [comment]
yeah i am looking at it now, i will test it and probably close it now.
testing of the SR was extremaly problematic since logs were either not saying anything usefull or missing info. I think tracing can fix that.
