### ISSUE TITLE
chore: update developer deployment - alternative setups

### ISSUE THREAD

**Issue by frondeus** [epiphany-platform/CommonDataLayer#567]
Acceptance criteria:

* [ ] There is separate configuration (in `.cdl` directory) for GRPC
* [ ] There is separate configuration for RabbitMQ
* [ ] There is documentation how to switch between different setups
* [ ] (optional) Horust deployment is up-to-date and compatible with the configuration.

**Comment by esavier** [comment]
643 is not fixing the issue

**Comment by luke-biel** [comment]
Conclusion of discussion:
* we will be keeping .cdl subfolder with postgres + kafka/grpc/rabbitmq configs
* we will add workflow that will check whether .cdl is up to date (generator requires non-interactive run method for that)
