### ISSUE TITLE
Rename Field::Array into something more clear like Field::SubObject

### ISSUE THREAD

**Issue by frondeus** [epiphany-platform/CommonDataLayer#617]
Field::Array is a bad name for the purpose this type is serving. Behavior it describes has nothing to do with arrays, it's job is to define a subobject in materialized view representation. If specific materializer does not support nested data it will flatten it(possible name collisions). Field::Array name is planned to be changed in the future(within phase II or shortly after it's finished).

Acceptance criteria:
* [x] Rename Field::Array into Field::SubObject
* [x] Fix acceptance tests

**Comment by frondeus** [comment]
This can be treated as Breaking Change, which requires 2.0.0. We need a decision from PO.

If we change this variant, we will also change an API - once created view would be no longer valid. It requires some kind of migration (although it requires only migrating view definitions, not the data itself). 

The one (and probably only approach) would be to accept both Array and SubObject as an alias (via serde(alias) attribute), and mark Array as deprecated one. Then anyone can schedule migration of existing data, in a non-locking manner (because OB, PUE, and the rest of the stack could still read deprecated values). We could also set up Schema Registry to accept both Array and 
SubObject but transform the old one into the newest name, so all new views would be converted on the fly.

This approach means we would defer releasing 2.0.0 (because alias means no breaking change... yet), but after all, as soon as we introduce the real Array field type, we are doomed.

Unless PO says:

Because Array field type depends heavily on relationships support and this feature is still marked as unfinished, it means it is not really a breaking change.

**Comment by esavier** [comment]
decided by po to make re-relase since this one is broken

**Comment by frondeus** [comment]
Fix has been merged in #625

**Comment by frondeus** [comment]
Should I close it now or wait for release?
