### ISSUE TITLE
docs: RFC for custom data passthrough

### ISSUE THREAD

**Issue by frondeus** [epiphany-platform/CommonDataLayer#648]
Based on discussion scheduled on 19.07.2021 regarding #635:

We need to design and describe a passthrough mechanism for metadata.
This metadata should be included as a separate field in CDLim:
```
{
  "objectId": "...",
  "schemaId": "...",
  "options": {
      "metadata": {
          "xyz": 3
      }
  },
  "payload": {}
}
```

This metadata should be passed through to notifications:
```
{
    "metadata": { // Another field in Notification
        "xyz": 3
    }
}
```

Acceptance Criteria:

- [ ] short RFC exists explaining functionality and approach

**Comment by esavier** [comment]
i would change it to `metadata.passthrough.{}` since its the logical description of what happens there, also it future proofs the behavior (something else may use metadata, or specific metadata that have to be stored in the future and it will be breaking change then

**Comment by esavier** [comment]
@pljadru
