### ISSUE TITLE
Get all views by relation returnd left-side

### ISSUE THREAD

**Issue by frondeus** [epiphany-platform/CommonDataLayer#651]
Found by running tests:

```
Error: status: Internal, message: "Critical error occured: get_all_views_by_relation sql query returned left-side", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 21 Jul 2021 12:39:31 GMT"} }
```

As far as I can tell, we should not use `fetch_many` in `schema_registry/db.rs:205`.

**Comment by luke-biel** [comment]
In mentioned place we use `fetch_many` when we should use `fetch` on QueryAs. If we change that, all issues should go away

**Comment by Kononnable** [comment]
https://github.com/epiphany-platform/CommonDataLayer/pull/654
