### ISSUE TITLE
Allow CDL timeseries repositories to receive message batches

### ISSUE THREAD

**Issue by luke-biel** [epiphany-platform/CommonDataLayer#69]
We need to alter command-service in such way that it's able to process batched messages.

Example message:
```json
{
    "schema_id": "...",
    "object_id": "...",
    "timestamp": 1233, // "CDL timestamp"
    "payload": [
        { "fields": { "f1": "...", "f2": "..." }, "ts": 1234 },
        { "fields": { "f1": "...", "f2": "..." }, "ts": 1234 },
        { "fields": { "f1": "...", "f2": "..." }, "ts": 1234 },
        { "fields": { "f1": "...", "f2": "..." }, "ts": 1234 },
        { "fields": { "f1": "...", "f2": "..." }, "ts": 1234 },
        { "fields": { "f1": "...", "f2": "..." }, "ts": 1234 },
        { "fields": { "f1": "...", "f2": "..." }, "ts": 1234 },
        { "fields": { "f1": "...", "f2": "..." }, "ts": 1234 },
        { "fields": { "f1": "...", "f2": "..." }, "ts": 1234 },
        { "fields": { "f1": "...", "f2": "..." }, "ts": 1234 }
    ]
}
```

This means that VM command-service must expect payload to be an array of objects, each object is converted into separate *line_protocol* entry and has its own timestamp. Then all these *LP* entries are inserted in single REST request.

_From that point inserting single message requires array with one element!_

DoD:
Command-service is able to insert multiple measurements in single request.

---

- [x] alter command-service payload deserialization
- [x] insert collected array into existing endpoint
- [x] write python tests to test your solution
- [x] write unit tests to cover deserialization and serialization

**Comment by damszew** [comment]
>This means that VM command-service must expect payload to be an array of objects (...). From that point inserting single message requires array with one element!

To be clear, batching should be done for all command-service "flavors" or only for victoria-metrics one?

**Comment by luke-biel** [comment]
> > This means that VM command-service must expect payload to be an array of objects (...). From that point inserting single message requires array with one element!
> 
> To be clear, batching should be done for all command-service "flavors" or only for victoria-metrics one?

Documents receive as is. If it's array, array gets stored. This affects only timeseries repositories, namely Druid and VM.
