### ISSUE TITLE
Integration test coverage

### ISSUE THREAD

**Issue by luke-biel** [epiphany-platform/CommonDataLayer#7]
* [ ] command service
    * [x] postgres
    * ~~[ ] sleigh~~
    * [x] victoria metrics
    * [ ] druid
* [ ] schema registry
* [ ] data router
* ~~[ ] blob storage~~
* ~~[ ] document storage~~
* [x] query service
* [x] db shrinker postgres
* [ ] leader elector
* [x] query router

This is parent issue of acceptance test coverage we need to implement
Order is from most important to least

**Comment by Kononnable** [comment]
Outdated
