### ISSUE TITLE
E2E application tests

### ISSUE THREAD

**Issue by luke-biel** [epiphany-platform/CommonDataLayer#8]
We have to implement basic E2E tests.

For now they should be ran manually from command line.

Scenario tested -
* insert data into data-router over RabbitMQ (*starting point*)
* data is rerouted to command-service based on schema
* command-service inserts data into PostgreSQL
* data is accessible through Postgres query-service over gRPC (*results*)

In the future we will cover more scenarios, message communication protocols and databases.

**Comment by frondeus** [comment]
@luke-biel Can you agree it has been done via #562?

**Comment by luke-biel** [comment]
Yeah, maybe not the exact scenario (we use Kafka, not RMQ), but I see no point in keeping this task open
