### ISSUE TITLE
k8s local deployment issue

### ISSUE THREAD

**Issue by johnbuonassisi** [epiphany-platform/CommonDataLayer#81]
Hi there, I work for ABB-Hitachi Powergrids and am trying out CDL for the first time.

I was following the instructions [here](https://github.com/epiphany-platform/CommonDataLayer/blob/develop/docs/k8s_local_deployment.md) to run CDL in a local k8s instance. I followed the instructions to run on my Ubuntu 20 VM. On CDL startup, most of the services were crashlooping. I noticed that helm/cdl/charts/templates/values-local.yaml is setting the **kafkaBrokers** to **infrastructure-kafka-headless**. After I changed this to the real name of the kafka pod, **infrastructure-kafka-0**, and restarted CDL, the services run successfully.

Note that I was using the develop branch.

I think this should be addressed so other people don't run into it. I am not k8s or helm expert so I am not sure what the right solution is.

**Comment by luke-biel** [comment]
`infrastructure-kafka-headless` is a service, while `infrastructure-kafka-0` is one of pods in this service. There should be no difference in running either.

CDL commonly crashes when it's 'spinning up' it's services, mainly because kafka needs time to warm up and accept connections. That's completly normal, k8s should handle restarting.
Is it possible that you've deployed altered `CDL` charts onto `Infrastructure` that had some time to let kafka startup? And the original deployment had no such time? This would explain the difference.

**Comment by johnbuonassisi** [comment]
Hmm, that would make sense. However, it seems that is not the case. Here is a test I just ran.

1. `Infrastructre` has been running for 22 hrs, along with altered `CDL`. All `CDL` services are running.
2. helm uninstall cdl, and wait for pods to terminate
3. revert helm chart to use `infrastructure-kafka-headless'
4. start cdl
5. observe crashlooping `cdl` services for 2 minutes
6. helm uninstall cdl
7. change helm chart to use `infrastructure-kafka-0`
8. start cdl
9. observe all `cdl` services running after 50 seconds 

Maybe the infrastructure-kafka-service is not configured correctly? I will take some time to understand k8s services better.

-> kubectl get services infrastructure-kafka-service
Name:              infrastructure-kafka-headless
Namespace:         default
Labels:            app.kubernetes.io/component=kafka
                   app.kubernetes.io/instance=infrastructure
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=kafka
                   helm.sh/chart=kafka-11.6.2
Annotations:       meta.helm.sh/release-name: infrastructure
                   meta.helm.sh/release-namespace: default
Selector:          app.kubernetes.io/component=kafka,app.kubernetes.io/instance=infrastructure,app.kubernetes.io/name=kafka
Type:              ClusterIP
IP Families:       <none>
IP:                None
IPs:               <none>
Port:              tcp-client  9092/TCP
TargetPort:        kafka-client/TCP
Endpoints:         172.17.0.4:9092
Port:              tcp-internal  9093/TCP
TargetPort:        kafka-internal/TCP
Endpoints:         172.17.0.4:9093
Session Affinity:  None
Events:            <none>

**Comment by johnbuonassisi** [comment]
I might be wrong about all this. Are there topics that need to be added to kafka before CDL will work properly?

**Comment by Kononnable** [comment]
Please check on new version of develop branch. Just remember to remove infrastructure helm chart and storage created by it beforehand(pv aren't removed by helm uninstall by default).

**Comment by jbuonassisi** [comment]
Thanks for the help, will try it out!
